name: Markdown Lint Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # equivalent cli: markdownlint-cli2  "**/*.md" "#**/CHANGELOG.md" "#.github/**" --config .markdownlint.json
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          config: .markdownlint.json
          fix: false
          globs: |
            **/*.md
            !**/CHANGELOG.md
            !.github/**
