name: Markdown Lint Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  markdownlint-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      # equivalent cli: markdownlint-cli2  "**/*.md" "#**/CHANGELOG.md" "#.github/**" --config .markdownlint.json
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22
        with:
          config: .markdownlint.json
          fix: false
          globs: |
            **/*.md
            !**/CHANGELOG.md
            !.github/**
