name: FOSSA scanning

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fossa:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install Ruby 3.4
        uses: ruby/setup-ruby@v1.267.0
        with:
          ruby-version: 3.4
      - name: Generate Gemfile.lock
        run: |
          echo "Finding all Gemfiles in the project..."
          echo "======================================="
          ORIGINAL_DIR=$(pwd)

          find . -type f -name "Gemfile" -not -path "*/example/*" | sort | while read gemfile; do
              gemfile_dir=$(dirname "$gemfile")
              
              # Change to the Gemfile's directory
              echo "Changing to directory: $gemfile_dir"
              
              cd "$gemfile_dir" || continue

              echo "Current directory: $(pwd)"
              echo "Creating lock file for: $gemfile"
              
              # Generate the gemlock files
              bundle lock || echo "Warning: Failed to generate lock file for $gemfile, continuing..."

              cd "$ORIGINAL_DIR" || exit 1
          done

      - uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # v1.7.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          team: OpenTelemetry
