name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

permissions:
  contents: read

jobs:
  stale:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby' }}
    permissions:
      issues: write # required for managing stale issues
      pull-requests: write # required for managing stale PRs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
      name: Clean up stale issues and PRs
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "ðŸ‘‹ This issue has been marked as stale because it has been open with no activity. You can: comment on the issue or remove the stale label to hold stale off for a while, add the `keep` label to hold stale off permanently, or do nothing. If you do nothing this issue will be closed eventually by the stale bot."
        stale-issue-label: "stale"
        exempt-issue-labels: "keep"
        days-before-issue-stale: 30
        days-before-issue-close: 30
        stale-pr-message: "ðŸ‘‹ This pull request has been marked as stale because it has been open with no activity. You can: comment on the issue or remove the stale label to hold stale off for a while, add the `keep` label to hold stale off permanently, or do nothing. If you do nothing this pull request will be closed eventually by the stale bot"
        stale-pr-label: "stale"
        exempt-pr-labels: "keep"
        days-before-pr-stale: 30
        days-before-pr-close: 30
